### ISSUE TITLE
Software spitting an error when checked the emergency alerts on

### ISSUE THREAD

**Issue by Pupswoof117** [openbroadcaster/obplayer#124]
I get an error as such when I try to check the setting and enable it, example this: 

`[May 13 2023 08:36:05 UTC] [error] Traceback (most recent call last):
  File "/home/allison/obplayer-5.2.0/obplayer/httpadmin/httpserver.py", line 254, in do_POST
    response = self.server.handle_post(request)
  File "/home/allison/obplayer-5.2.0/obplayer/httpadmin/httpserver.py", line 122, in handle_post
    return view(request)
  File "/home/allison/obplayer-5.2.0/obplayer/httpadmin/httpadmin.py", line 218, in req_alert_list
    return obplayer.alerts.Processor.get_alerts()
AttributeError: 'NoneType' object has no attribute 'get_alerts'`

Is there a dependency I missed? I installed the base ones. What else do I need? I got it off of Git and am running it on a PC running 20.04 in my bedroom.

**Comment by radiorob** [comment]
https://github.com/openbroadcaster/obplayer/releases/tag/5.3.0
