### ISSUE TITLE
TypeError: GObject.__init__() takes exactly 0 arguments (1 given)

### ISSUE THREAD

**Issue by EvansMike** [openbroadcaster/obplayer#33]
python3  obplayer.py -d
[Jun 04 2020 18:01:10 UTC] [module] loading module player
[Jun 04 2020 18:01:10 UTC] [debug] adding element to bin: audio-out-capsfilter
[Jun 04 2020 18:01:10 UTC] [debug] adding element to bin: audio-out-level
[Jun 04 2020 18:01:10 UTC] [debug] adding element to bin: audio-out-interlink-tee
[Jun 04 2020 18:01:10 UTC] [debug] adding element to bin: audio-out-post-tee-queue
[Jun 04 2020 18:01:10 UTC] [debug] adding element to bin: audiosink
[Jun 04 2020 18:01:10 UTC] [error] exception occurred in main thead. Terminating...
[Jun 04 2020 18:01:10 UTC] [error] Traceback (most recent call last):
File "/home/mikee/Projects/obplayer/obplayer/main.py", line 86, in start
self.load_module('player')
File "/home/mikee/Projects/obplayer/obplayer/main.py", line 207, in load_module
exec('import obplayer.%s; obplayer.%s.init()' % (name, name))
File "<string>", line 1, in <module>
File "/home/mikee/Projects/obplayer/obplayer/player/__init__.py", line 31, in init
obplayer.Player = ObPlayer()
File "/home/mikee/Projects/obplayer/obplayer/player/control.py", line 61, in __init__
self.player_init()
File "/home/mikee/Projects/obplayer/obplayer/player/control.py", line 82, in player_init
self.pipes['testsignal'] = pipes.ObTestSignalPipeline('test-signal', self)
File "/home/mikee/Projects/obplayer/obplayer/player/pipes/testsignal.py", line 43, in __init__
self.pipeline = Gst.Pipeline(name)
TypeError: GObject.__init__() takes exactly 0 arguments (1 given)

**Comment by EvansMike** [comment]
on Fedora31

**Comment by cchapman900** [comment]
Also getting this on Ubuntu 20.04
