### ISSUE TITLE
ObPlayer - Fresh Install On Xununtu 20.04 Webui Will Not Load

### ISSUE THREAD

**Issue by Terris96** [openbroadcaster/obplayer#59]
Laptop with a fresh install of Xununtu 18.04.05 upgraded to 20.04.  Installed listed dependicies and starting OBPlay plays the test tone.  When I attempt to access the webui, get prompted for the default admin password.  Site takes the password and the indicates that the connection was reset.  Never able to login to the Webui locally or from another PC.  Any suggetions?

This is the third time I have re-installed, all with the same issues.

Thanks

**Comment by vincentthedev** [comment]
Can you please provide the version, and branch of the player your using? You can find the version in the VERSION file, and the branch can be found by running ```bash
git status
```
This info is needed to track down the issue. Thank you for help in this matter.

**Comment by Terris96** [comment]
Version 5.1.1-20211116

Git Status shows :  On branch master

**Comment by Terris96** [comment]
Here is the error I get in the Terminal window when running obplayer and trying to get to the webui

alert@Alert-PC:~$ cd ..
alert@Alert-PC:/home$ cd ..
alert@Alert-PC:/$ cd usr
alert@Alert-PC:/usr$ cd share
alert@Alert-PC:/usr/share$ cd obplayer-main
alert@Alert-PC:/usr/share/obplayer-main$ bash obplayer_check
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45610)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 429, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 187, in do_GET
    if self.check_authorization() == False:
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 162, in check_authorization
    elif username == self.server.username and obplayer.Password_System.login_check(password.encode('utf-8'), self.server.password_hash):
AttributeError: module 'obplayer' has no attribute 'Password_System'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45612)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 187, in do_GET
    if self.check_authorization() == False:
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 162, in check_authorization
    elif username == self.server.username and obplayer.Password_System.login_check(password.encode('utf-8'), self.server.password_hash):
AttributeError: module 'obplayer' has no attribute 'Password_System'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45614)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 187, in do_GET
    if self.check_authorization() == False:
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 162, in check_authorization
    elif username == self.server.username and obplayer.Password_System.login_check(password.encode('utf-8'), self.server.password_hash):
AttributeError: module 'obplayer' has no attribute 'Password_System'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45616)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 187, in do_GET
    if self.check_authorization() == False:
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 162, in check_authorization
    elif username == self.server.username and obplayer.Password_System.login_check(password.encode('utf-8'), self.server.password_hash):
AttributeError: module 'obplayer' has no attribute 'Password_System'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45618)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 187, in do_GET
    if self.check_authorization() == False:
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 162, in check_authorization
    elif username == self.server.username and obplayer.Password_System.login_check(password.encode('utf-8'), self.server.password_hash):
AttributeError: module 'obplayer' has no attribute 'Password_System'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45620)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 187, in do_GET
    if self.check_authorization() == False:
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 162, in check_authorization
    elif username == self.server.username and obplayer.Password_System.login_check(password.encode('utf-8'), self.server.password_hash):
AttributeError: module 'obplayer' has no attribute 'Password_System'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45622)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 187, in do_GET
    if self.check_authorization() == False:
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 162, in check_authorization
    elif username == self.server.username and obplayer.Password_System.login_check(password.encode('utf-8'), self.server.password_hash):
AttributeError: module 'obplayer' has no attribute 'Password_System'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45624)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 187, in do_GET
    if self.check_authorization() == False:
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 162, in check_authorization
    elif username == self.server.username and obplayer.Password_System.login_check(password.encode('utf-8'), self.server.password_hash):
AttributeError: module 'obplayer' has no attribute 'Password_System'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45626)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 187, in do_GET
    if self.check_authorization() == False:
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 162, in check_authorization
    elif username == self.server.username and obplayer.Password_System.login_check(password.encode('utf-8'), self.server.password_hash):
AttributeError: module 'obplayer' has no attribute 'Password_System'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45628)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 187, in do_GET
    if self.check_authorization() == False:
  File "/usr/share/obplayer-main/obplayer/httpadmin/httpserver.py", line 162, in check_authorization
    elif username == self.server.username and obplayer.Password_System.login_check(password.encode('utf-8'), self.server.password_hash):
AttributeError: module 'obplayer' has no attribute 'Password_System'
----------------------------------------
^Calert@Alert-PC:/usr/share/obplayer-main$

**Comment by vincentthedev** [comment]
Thank you for posting your logs that's a big help in tracking down a issue. Sorry your having this issue. It is a known issue which when it's fixed I'll update this issue to let you know.

**Comment by Terris96** [comment]
Where this is handling emergency alerts for our radio station I would like to get it going.  Any sort or work-arounds, or is there an older version of obplayer that still works that you know of?

Thanks

**Comment by vincentthedev** [comment]
You can try using the bix fix branch of the code for now. This a issue with the new password system. You will likely need to changes both when switching to this branch and when switching over of it after the main branch has a fix.

You can replace make the code by using the following command. Please note you will need to the "YOUR_FOLDER" to where the player is installed.

```bash
cd YOUR_FOLDER && git clone git@github.com:openbroadcaster/obplayer.git -b bug-fix
```

Please let me know if that fixes your issue.
Thanks!

**Comment by vincentthedev** [comment]
The issue been fixed in the main branch. Please clone the main when ready.
Thanks for the report.

**Comment by Terris96** [comment]
Now getting a new error:
alert@Alert-PC:/usr/share/obplayer-main$ bash obplayer_check
Traceback (most recent call last):
  File "obplayer.py", line 23, in <module>
    import obplayer
  File "/usr/share/obplayer-main/obplayer/__init__.py", line 30, in <module>
    import obplayer.password_system as password_system
  File "/usr/share/obplayer-main/obplayer/password_system.py", line 1, in <module>
    import passlib.hash as hashing
ModuleNotFoundError: No module named 'passlib'

**Comment by vincentthedev** [comment]
You need to install passlib with bcrypt support. You can install it using pip, or pip3 depending on your system. Below is both commands please trying running them and restarting your player.

```bash
sudo pip install passlib[bcrypt]
```

```bash
sudo pip3 install passlib[bcrypt]
```

If you get a error about pip not being installed. Please install it using the following command:
```bash
sudo apt install python3-pip
```

Thanks!

**Comment by vincentthedev** [comment]
That's actually a new error. So you got it installed. It looks like you will need the settings didn't update from the player upgrade. 
I'll have to push a patch to handle the mover over so creates the default login under the new system.

I'll update you shortly. The full reset would fix this but I'm guessing you would prefer to wait a patch. If not though, you can do a full settings reset by running:
```bash
rm ~/.openbroadcaster/settings.db
```

**Comment by vincentthedev** [comment]
I've now added the code to handle a move from the old password system to the new one. Please run a git pull to update your player. You should ensure your in the player's main folder before running git pull.

**Comment by Terris96** [comment]
Seems to be working now.  Thanks for all the help.
